name: Scheduled Workflow

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run audit
        run: npm audit --audit-level=high
